[[servers]]
path = "/tmp/wg0.conf"
name = "wg0"
address = "10.20.30.x"
subnet = 24
port = 51823
prikey = "OBkqW24qErlzApKZinmPdzHP0qUleF4YnjH1RdoSOW4="
pubkey = "EXhJU4LlShp9l0hOcuMFVxFOx/XztW36LNayjcR+xSM="
peers = []

[[servers]]
path = "/tmp/wg1.conf"
name = "wg1"
address = "10.11.12.x"
subnet = 24
port = 51824
prikey = "0K+kGmivTvzr1sT/hhqLdFdSVrODteaoo+dKUTrLmUM="
pubkey = "ly4PCBsf7CdAkZaAnT+PkksMwlScZvNrCRRuPj976FE="

[[servers.peers]]
name = "peer1"
address = "10.11.12.2/24"
prikey = "qHSMnsD6lxMZy4HVV9ronhSbmVd11AQzOBD4/UXm+E4="
pubkey = "lqLptyeQfXwK+93tU9okHkN0sarzgEp78pFzRpUlsjo="
enabled = true
